#
GET http://localhost:3000/api/produtos
Content-Type: application/json
###

# Inserir novo produto
POST http://localhost:3000/api/produtos
Content-Type: application/json

{
 "tipo": "alimentos", 
 "nome": "melancia",
 "valor": 7.75
}
###


# Alterar produto
PUT http://localhost:3000/api/produtos
Content-Type: application/json

{
 "_id": "626adb33d7b4b7f28032118d",
 "tipo": "alimentos",
 "nome": "abacaxiii",
 "valor": 5.99
}
###


# Excluir um produto
DELETE http://localhost:3000/api/produtos/626adb33d7b4b7f28032118d
Content-Type: application/json
###


# Obter pelo id de produto
GET http://localhost:3000/api/produtos/626ade502359f520b75f6f37
Content-Type: application/json
###


# Obter produtos filtrando
GET http://localhost:3000/api/produtos/filtro/salada
Content-Type: application/json
###